# Python for Spatial Analysis
## Second part of the module of GG3209 Spatial Analysis with GIS.
### Notebook to practice NumPy and Pandas - Exercises

---
Dr Fernando Benitez -  University of St Andrews - School of Geography and Sustainable Development - Second Iteration 2023 v.2.0 

# Practicing NumPy

## 2.0 
Import numpy under the alias `np`.

In [1]:
import numpy as np

## 2.1 

Create the following arrays:

* Create an array of 10 ones.

* Create an array of the integers 1 to 20.

* Create a 5 x 5 matrix of ones with a dtype int.

In [2]:
arr1 = np.ones((1, 10))
print(arr1)
print("==========")

arr2 = np.linspace(1, 20, 20, dtype = "int")
print(arr2)
print("==========")

arr3 = np.ones((1, 5, 5))
print(arr3)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


## 2.2 
Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [3]:
arr4 = np.random.randn(3, 3, 3)
print(arr4)

[[[ 1.11074053  0.92401604  1.8780083 ]
  [ 0.13626987 -1.39495739 -0.20757104]
  [ 0.39045696 -0.47109976 -0.1504489 ]]

 [[-0.38734032 -0.77687431  2.16472813]
  [-0.32184837 -0.09767252  0.84826437]
  [ 0.77473628  0.59476939 -1.70348231]]

 [[-0.18557641 -0.47768237  0.65898696]
  [ 0.85866299  0.38301601  1.01618267]
  [-0.3137467  -1.75730846 -0.51598037]]]


# 2.3 

Create an array of 20 linearly spaced numbers between 1 and 10.

In [4]:
arr5 = np.linspace(1, 10, 20, dtype="int")
print(arr5)

[ 1  1  1  2  2  3  3  4  4  5  5  6  6  7  7  8  8  9  9 10]


## 2.4

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [5]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [24]:
20

20

In [6]:
print(a[3, 4])

20


```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [7]:
print(a[1:5, 3:5])


[[ 9 10]
 [14 15]
 [19 20]
 [24 25]]


```python
array([ 6,  7,  8,  9, 10])
```

In [40]:
print(a[1:2, 0:5])

[[ 6  7  8  9 10]]


## 2.5 

Calculate the sum of all the numbers in `a`.

In [6]:
print(a)
areshape = np.reshape(a, -1)
print(areshape)
sum = 0
for i in areshape:
    sum += i
print(sum)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
325


## 2.6 

Calculate the sum of each row in `a`.

In [7]:
print(a)

row1 = np.reshape(a[0:1, 0:5], -1)
row2 = np.reshape(a[1:2, 0:5], -1)
row3 = np.reshape(a[2:3, 0:5], -1)
row4 = np.reshape(a[3:4, 0:5], -1)
row5 = np.reshape(a[4:5, 0:5], -1)

print(row1)
print(row2)
print(row3)
print(row4)
print(row5)

row = row1
sum = 0
for i in row:
    sum += i
print(sum)

row = row2
sum = 0
for i in row:
    sum += i
print(sum)

row = row3
sum = 0
for i in row:
    sum += i
print(sum)

row = row4
sum = 0
for i in row:
    sum += i
print(sum)

row = row5
sum = 0
for i in row:
    sum += i
print(sum)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]
[16 17 18 19 20]
[21 22 23 24 25]
15
40
65
90
115


In [40]:
print(a)
num_rows, num_cols = a.shape
#print(num_rows)
#print(num_cols)

for i in a:
    sum = 0
    for j in i:
        sum += j
    print(i)
    print(sum)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[1 2 3 4 5]
15
[ 6  7  8  9 10]
40
[11 12 13 14 15]
65
[16 17 18 19 20]
90
[21 22 23 24 25]
115


## 2.7 

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [24]:
import pandas as pd
amean = a.mean()
print(amean)
areshape = np.reshape(a, -1)

#for i in areshape:
    #if i > amean:
        #areshape.delete(i)
#print(areshape)

aless = a[a > amean]
print(aless)

for i in areshape:
    if i == aless.any():
        areshape.pop(i)
    

13.0
[14 15 16 17 18 19 20 21 22 23 24 25]


AttributeError: 'numpy.ndarray' object has no attribute 'pop'

# Practicing Pandas

## 2.8

In this set of practice exercises we'll be investigating the carbon footprint of different foods. 

We'll be leveraging a dataset compiled by [Kasia Kulma](https://r-tastic.co.uk/post/from-messy-to-tidy/) and contributed to [R's Tidy Tuesday project](https://github.com/rfordatascience/tidytuesday).

Start by importing pandas with the alias `pd`.

In [10]:
import pandas as pd

## 2.9 

The dataset we'll be working with has the following columns:

|column      |description |
|:-------------|:-----------|
|country       | Country Name |
|food_category | Food Category |
|consumption   | Consumption (kg/person/year) |
|co2_emmission | Co2 Emission (Kg CO2/person/year) |


Import the dataset as a dataframe named `df` from this url: <https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv>

In [11]:
cf_df = pd.read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv', sep=",", header=0, encoding="ISO-8859-1")


## 2.10 

How many rows and columns are there in the dataframe?

In [65]:
print(cf_df.shape)

1430
(1430, 4)


In [26]:
cf_df.head(10)

country             food_category  consumption  co2_emmission
0  Argentina                      Pork        10.51          37.20
1  Argentina                   Poultry        38.66          41.53
2  Argentina                      Beef        55.48        1712.00
3  Argentina               Lamb & Goat         1.56          54.63
4  Argentina                      Fish         4.36           6.96
5  Argentina                      Eggs        11.39          10.46
6  Argentina        Milk - inc. cheese       195.08         277.87
7  Argentina  Wheat and Wheat Products       103.11          19.66
8  Argentina                      Rice         8.77          11.22
9  Argentina                  Soybeans         0.00           0.00

## 2.11

What is the mean `co2_emission` of the whole dataset?

In [32]:
print(cf_df["co2_emmission"])
cf_df["co2_emmission"].mean()

0         37.20
1         41.53
2       1712.00
3         54.63
4          6.96
         ...   
1425      31.21
1426       3.33
1427     219.76
1428       0.27
1429       1.27
Name: co2_emmission, Length: 1430, dtype: float64


74.383993006993

## 2.12

What is the maximum `co2_emmission` in the dataset and which food type and country does it belong to?

In [12]:
maxco2 = cf_df["co2_emmission"].max()
print(maxco2)
print(cf_df.iloc[maxco2])

1712.0


TypeError: Cannot index by location index with a non-integer key

## 2.13

How many countries produce more than 1000 Kg CO2/person/year for at least one food type?

In [50]:
flco2 = pd.to_numeric(cf_df["co2_emmission"])
kg1000 = cf_df[flco2 > 1000]
kg1 = cf_df[flco2 < 1000]
print(kg1000)
print("==========")
print(kg1)

       country food_category  consumption  co2_emmission
2    Argentina          Beef        55.48        1712.00
13   Australia          Beef        33.86        1044.85
57         USA          Beef        36.24        1118.29
90      Brazil          Beef        39.25        1211.17
123    Bermuda          Beef        33.15        1022.94
         country             food_category  consumption  co2_emmission
0      Argentina                      Pork        10.51          37.20
1      Argentina                   Poultry        38.66          41.53
3      Argentina               Lamb & Goat         1.56          54.63
4      Argentina                      Fish         4.36           6.96
5      Argentina                      Eggs        11.39          10.46
...          ...                       ...          ...            ...
1425  Bangladesh        Milk - inc. cheese        21.91          31.21
1426  Bangladesh  Wheat and Wheat Products        17.47           3.33
1427  Bangladesh   

## 2.14

Which country consumes the least amount of beef per person per year?


In [67]:
food = cf_df[["food_category", "country"]]
print(food)
#beef = cf_df.pop(cf_df.food_category != "Beef")
print(beef)

                 food_category     country
0                         Pork   Argentina
1                      Poultry   Argentina
2                         Beef   Argentina
3                  Lamb & Goat   Argentina
4                         Fish   Argentina
...                        ...         ...
1425        Milk - inc. cheese  Bangladesh
1426  Wheat and Wheat Products  Bangladesh
1427                      Rice  Bangladesh
1428                  Soybeans  Bangladesh
1429   Nuts inc. Peanut Butter  Bangladesh

[1430 rows x 2 columns]


KeyError: True

## 2.15

What is the total emissions of all the meat products (Pork, Poultry, Fish, Lamb & Goat, Beef) in the dataset combined?

In [ ]:
# code comes here

# 2.16 

What is the total emissions of all other (non-meat) products in the dataset combined?

In [ ]:
# code comes here

## Well done!

That's all from this week, if you have any questions, do not forget to ask the TAs for assistance.